### ISSUE TITLE
Review and republish 8.1.2.1

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Sitecore.Support.131687#4]
Due to a bug in ReleaseDaemon 1.0.5 the Sitecore.Support.131687-8.1.2.1 didn't have compatibility section. Now when ReleaseDaemon 1.0.5.1 hotfixed this issue, I re-generated the Sitecore.Support.131687-8.1.2.1 release in order to verify that the bug is fixed. Please review and publish the release if everything is accurate.

**Comment by ob1dev** [comment]
Done.
